# Generated by Django 4.1.3 on 2025-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportapplication',
            name='cargo_type',
            field=models.CharField(max_length=512, verbose_name='Характер груза'),
        ),
        migrations.AlterField(
            model_name='transportapplication',
            name='recipient',
            field=models.CharField(max_length=512, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='transportapplication',
            name='sender',
            field=models.CharField(max_length=512, verbose_name='Отправитель'),
        ),
    ]
