# Generated by Django 4.1.3 on 2025-07-14 09:30

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_transportapplication_cargo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsoffer',
            name='amount',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Стоимость доставки'),
        ),
    ]
