# Generated by Django 4.1.3 on 2025-07-14 09:41

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_invoicepayment_amount_alter_paymentorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='amount',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='total',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма'),
        ),
    ]
