# Generated by Django 4.1.3 on 2025-06-13 09:04

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_companyactivitytype_rec_col_types'),
        ('exchange', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsStatisticsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('price', common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за единицу веса')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_statistics_mark', to='exchange.recyclablesapplication', verbose_name='Заявка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_statistics_mark', to='company.company', verbose_name='Компания')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
