# Generated by Django 4.1.3 on 2025-06-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_contractsstatisticsmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsstatisticsmark',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_statistics_mark', to='exchange.recyclablesapplication', verbose_name='Заявка'),
        ),
    ]
