# Generated by Django 4.1.3 on 2025-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_contractsstatisticsmark_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsstatisticsmark',
            name='application',
        ),
        migrations.RemoveField(
            model_name='contractsstatisticsmark',
            name='company',
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='company_id',
            field=models.IntegerField(default=1, verbose_name='Id компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='company_name',
            field=models.CharField(default=1, max_length=512, verbose_name='Название компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='deal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Покупка'), (2, 'Продажа')], default=1, verbose_name='Тип сделки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='recyclable_application_id',
            field=models.IntegerField(default=1, verbose_name='Id заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='recyclable_category_id',
            field=models.IntegerField(default=1, verbose_name='Id категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='recyclable_category_name',
            field=models.CharField(default=1, max_length=512, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='recyclable_id',
            field=models.IntegerField(default=1, verbose_name='Id фракции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsstatisticsmark',
            name='recyclable_name',
            field=models.CharField(default=1, max_length=512, verbose_name='Название фракции'),
            preserve_default=False,
        ),
    ]
