# Generated by Django 4.1.3 on 2025-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_contractsstatisticsmark_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclablesapplication',
            name='application_recyclable_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не проверенная'), (2, 'Проверенная'), (3, 'Надежная'), (4, 'Ненадёжная'), (5, 'На удаление')], default=1, verbose_name='Статус Фракции'),
        ),
    ]
