# Generated by Django 4.1.3 on 2025-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_recyclablesapplication_application_recyclable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentapplication',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
