# Generated by Django 4.1.3 on 2025-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_equipmentapplication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclablesapplication',
            name='application_recyclable_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Отходы'), (2, 'Гранула')], default=1, verbose_name='Статус Фракции'),
        ),
    ]
