# Generated by Django 4.1.3 on 2025-07-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_recyclablesapplication_application_recyclable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'На проверке'), (2, 'Опубликована'), (3, 'Завершена'), (4, 'Отклонена'), (5, 'Удалено перманентно')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='recyclablesapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'На проверке'), (2, 'Опубликована'), (3, 'Завершена'), (4, 'Отклонена'), (5, 'Удалено перманентно')], default=1, verbose_name='Статус'),
        ),
    ]
