# Generated by Django 4.1.3 on 2025-07-14 09:48

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_alter_contractsstatisticsmark_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsstatisticsmark',
            name='price',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена за единицу веса'),
        ),
        migrations.AlterField(
            model_name='equipmentapplication',
            name='price',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='equipmentdeal',
            name='price',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='recyclablesapplication',
            name='price',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена за единицу веса'),
        ),
        migrations.AlterField(
            model_name='recyclablesdeal',
            name='price',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена за единицу веса'),
        ),
    ]
