# Generated by Django 4.1.3 on 2024-12-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_recyclables_recycling_code'),
        ('exchange', '0026_equipmentapplication_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentapplication',
            name='equipment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipmentapplication',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='category_applications', to='product.equipmentcategory', verbose_name='Категория оборудование'),
        ),
    ]
