# Generated by Django 4.1.3 on 2024-12-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_recyclables_recycling_code'),
        ('exchange', '0027_alter_equipmentapplication_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentapplication',
            old_name='equipment_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='equipmentapplication',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_applications', to='product.equipment', verbose_name='Оборудование'),
        ),
    ]
