# Generated by Django 4.1.3 on 2025-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_rename_equipment_category_equipmentapplication_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclablesapplication',
            name='application_recyclable_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Отходы'), (2, 'Гранула')], default=1, verbose_name='Статус Фракции'),
        ),
    ]
