# Generated by Django 4.1.3 on 2025-03-17 14:55

import common.model_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_alter_proposal_special_id_equipmentproposal'),
        ('exchange', '0029_recyclablesapplication_application_recyclable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('shipping_address', models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес отгрузки')),
                ('shipping_latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта адреса отгрузки')),
                ('shipping_longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота адреса отгрузки')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес доставки')),
                ('delivery_latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта адреса доставки')),
                ('delivery_longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота адреса доставки')),
                ('with_nds', models.BooleanField(default=False, verbose_name='С НДС')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('video_url', models.CharField(blank=True, default='', max_length=512, verbose_name='Ссылка на видео')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'День'), (2, '2 Дня'), (3, '4 Дня'), (4, '7 Дней')], default=1, verbose_name='Период специальной заявки')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена специальной заявки')),
            ],
            options={
                'verbose_name': 'Специальная заявка',
                'verbose_name_plural': 'Специальные заявки',
                'db_table': 'special_applications',
            },
        ),
        migrations.CreateModel(
            name='SpecialApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_end', models.DateTimeField(verbose_name='Дата окончания специальной заявки')),
                ('time_begin', models.DateTimeField(verbose_name='Дата начала специальной заявки')),
                ('payment_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер платежа')),
                ('payment_access', models.BooleanField(blank=True, default=False, null=True, verbose_name='Успешность платежа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('special_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.specialapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='specialapplication',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies_special_applications', through='exchange.SpecialApps', to='company.company', verbose_name='Специальные заявки компаний'),
        ),
    ]
