# Generated by Django 4.1.3 on 2025-03-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0030_specialapplication_specialapps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialApplicationPaidPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена за период')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='specialapplication',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='exchange.specialapplicationpaidperiod', verbose_name='Период'),
        ),
    ]
