# Generated by Django 4.1.3 on 2025-03-21 07:16

import common.model_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_alter_proposal_special_id_equipmentproposal'),
        ('exchange', '0031_specialapplicationpaidperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialapplication',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='specialapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='specialapplication',
            name='latitude',
            field=common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='specialapplication',
            name='longitude',
            field=common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
