# Generated by Django 4.1.3 on 2025-04-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_options'),
        ('exchange', '0033_specialapplication_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialapplication',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_app', to='chat.chat', verbose_name='Чат специльного предложения'),
        ),
    ]
