# Generated by Django 4.1.3 on 2025-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companyactivitytype_rec_col_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyactivitytype',
            name='rec_col_types',
            field=models.ManyToManyField(blank=True, related_name='recyclables_collection_types', to='company.recyclingcollectiontype', verbose_name='Тип сбора/переработки'),
        ),
    ]
