# Generated by Django 4.1.3 on 2025-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyactivitytype_rec_col_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyactivitytype',
            name='rec_col_types',
            field=models.ManyToManyField(blank=True, to='company.recyclingcollectiontype', verbose_name='Тип сбора/переработки'),
        ),
    ]
