# Generated by Django 4.1.3 on 2025-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_companyactivitytype_rec_col_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не проверенная'), (2, 'Проверенная'), (3, 'Надежная'), (4, 'Ненадёжная'), (5, 'На удаление')], default=1, verbose_name='Статус'),
        ),
    ]
