# Generated by Django 4.1.3 on 2025-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecyclables',
            name='company_recyclable_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Отходы'), (2, 'Гранула')], default=1, verbose_name='Статус Фракции'),
        ),
    ]
