# Generated by Django 4.1.3 on 2025-07-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_companyrecyclables_company_recyclable_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrecyclables',
            old_name='company_recyclable_status',
            new_name='application_recyclable_status',
        ),
    ]
