# Generated by Django 4.1.3 on 2025-07-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_rename_company_recyclable_status_companyrecyclables_application_recyclable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecyclables',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
    ]
