# Generated by Django 4.1.3 on 2025-07-14 09:41

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_companyrecyclables_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecyclables',
            name='price',
            field=common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Цена'),
        ),
    ]
