# Generated by Django 4.1.3 on 2025-01-30 15:17

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_rename_equipment_category_equipmentapplication_category_and_more'),
        ('company', '0018_alter_company_bank_name_alter_company_bic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Эконом'), (2, 'Стандартный'), (3, 'Расширенный'), (4, 'Абсолют')], default=1, verbose_name='Подписки')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Месяц'), (2, '3 Месяца'), (3, '9 Месяцев'), (4, 'Год')], default=1, verbose_name='Период подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'subscribes',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не проверенная'), (2, 'Проверенная'), (3, 'Надежная'), (4, 'Ненадёжная')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='recyclingcollectiontype',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.CreateModel(
            name='SubscribesCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_end', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('time_begin', models.DateTimeField(verbose_name='Дата начала подписки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.subscribe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscribe',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies_subscribes', through='company.SubscribesCompanies', to='company.company', verbose_name='Подписки компаний'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('special_id', models.CharField(max_length=2551)),
                ('applications', models.ManyToManyField(blank=True, related_name='applications', to='exchange.recyclablesapplication', verbose_name='Заявки из рассылок')),
                ('companies', models.ManyToManyField(blank=True, related_name='companies', to='company.company', verbose_name='Компании из рассылок')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'db_table': 'proposals',
            },
        ),
    ]
