# Generated by Django 4.1.3 on 2025-01-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_subscribe_alter_company_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена подписки'),
        ),
        migrations.AddField(
            model_name='subscribescompanies',
            name='payment_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Успешность платежа'),
        ),
        migrations.AddField(
            model_name='subscribescompanies',
            name='payment_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер платежа'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Месяц'), (2, '3 Месяца'), (3, '6 Месяцев'), (4, 'Год')], default=1, verbose_name='Период подписки'),
        ),
    ]
