# Generated by Django 4.1.3 on 2025-03-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_rename_equipment_category_equipmentapplication_category_and_more'),
        ('company', '0020_subscribe_price_subscribescompanies_payment_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='special_id',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EquipmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('special_id', models.CharField(max_length=255)),
                ('applications', models.ManyToManyField(blank=True, related_name='equipments_applications', to='exchange.equipmentapplication', verbose_name='Заявки из рассылок')),
                ('companies', models.ManyToManyField(blank=True, related_name='equipments_companies', to='company.company', verbose_name='Компании из рассылок')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_proposals', to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Предложение по оборудованию',
                'verbose_name_plural': 'Предложения по оборудованию',
                'db_table': 'equipments_proposals',
            },
        ),
    ]
