# Generated by Django 4.1.3 on 2025-04-06 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0021_alter_proposal_special_id_equipmentproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_company', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
