# Generated by Django 4.1.3 on 2025-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='staff',
        ),
    ]
