# Generated by Django 4.1.3 on 2025-04-08 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_remove_company_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
