# Generated by Django 4.1.3 on 2025-04-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_account',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Расчетный счет'),
        ),
    ]
