# Generated by Django 4.1.3 on 2025-06-22 06:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('action', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Создать'), (2, 'Изменение'), (3, 'Удаление'), (4, 'Вход'), (5, 'Выход')], default='', verbose_name='Действие')),
                ('action_model', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Компания'), (2, 'Контракт готов к отгрузке'), (3, 'Контракт на поставку'), (4, 'Заявка на оборудование'), (5, 'Сделка по вторсырью'), (6, 'Сделка по оборудованию'), (7, 'Предложение по вторсырью'), (8, 'Предложение по оборудованию'), (9, 'Перевозчик')], default='', verbose_name='Объект действия')),
                ('model_id', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('updated_fields', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Действия пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'db_table': 'users_actions',
            },
        ),
    ]
