# Generated by Django 4.1.3 on 2025-06-22 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractions',
            name='model_id',
            field=models.TextField(blank=True, default='', verbose_name='Id экземпляра модели'),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='updated_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None),
        ),
    ]
