# Generated by Django 4.1.3 on 2025-04-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_staff'),
        ('user', '0006_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_company', to='company.company', verbose_name='Сотрудники'),
        ),
    ]
