# Generated by Django 4.1.3 on 2025-04-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_company_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Супер-Администратор ВторПрайс'), (2, 'Администратор ВторПрайс'), (3, 'Менеджер ВторПрайс'), (4, 'Логист ВторПрайс'), (5, 'Владелец компании'), (6, 'Сотрудник компании')], default=5, verbose_name='Роль'),
        ),
    ]
